## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [9]:
import pandas as pd
import numpy as np

data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

#1
print("question 1 below")
df = pd.DataFrame(data)
pd.set_option('display.max_columns', None)
print(df)

#2
print("question 2 below")
df3 = df[df['job'].isin(['teacher', 'psychologist'])]
df4 = df3[df3['num_cars']>df3['family_size']]
print(df4)

#3
print("question 3 below")
df5 = df[df['family_size']<=2]
df6= df5[df5['num_cars']>=1]
print(df6)

#4
print("question 4 below")
print(len(df['job'].unique()))

question 1 below
     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
question 2 below
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
question 3 below
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
question 4 below
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [10]:
import pandas as pd
import numpy as np
fruits = np.random.choice(['apple', 'banana', 'carrot'], 10).reshape(10,)
weights = np.linspace(1, 10, 10).reshape(10,)

df = pd.DataFrame(fruits, columns=['fruits'])
df['weights'] = weights

unique_fruits = df['fruits'].unique()
print(unique_fruits)
for i in unique_fruits:
    print(i, df.loc[df['fruits'] == i, 'weights'].mean())

['apple' 'banana' 'carrot']
apple 4.4
banana 3.0
carrot 7.5


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [11]:
#1
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

i = np.argsort(course_name)
print(i)
#2
for p in course_name:
    if p[0] == 'P':
        print(p + " Starts with P")

[1 3 0 2 4]
Python Starts with P
PHP Starts with P


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [15]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

#1
reverse = student_id[::1]
print("Original array: " + str(student_id))
print("Reversed array: " + str(reverse))

#2
sorted_indices = np.argsort(student_id)
sorted_array = student_id[sorted_indices]
print("3 largest values "+ str(sorted_array[-3]))

Original array: [1023 5202 6230 1671 1682 5241 4532]
Reversed array: [1023 5202 6230 1671 1682 5241 4532]
3 largest values 5202


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [12]:
import numpy as np
x = np.arange(1, 100)
# find  multiple of 3/ 5
n= x[(x % 3 == 0) | (x % 5 == 0)]
print(n[:1000])
# print sum 
print(n.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

In [13]:
#1
import numpy as np

print("Original array:")
arr = np.arange(12).reshape(3,4)
print(arr)


arr[:, [2, 1]] = arr[:, [1, 2]]
print("Swapped column 1 and 2")
print(arr)

#2
arr[[0, 1], :] = arr[[1, 0], :]
print("Swapped row 0 and 1")
print(arr)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped column 1 and 2
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Swapped row 0 and 1
[[ 4  6  5  7]
 [ 0  2  1  3]
 [ 8 10  9 11]]
